apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
stringData:
  # Base64 não é necessário se usar stringData
  DB_PASSWORD: "sua-senha-super-segura"
  STRIPE_API_KEY: "sk_live_..."
  KAFKA_SASL_PASSWORD: "senha-do-kafka"
