name: ci_projeto

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # Define o Kafka como um serviço que roda ao lado do seu job
    services:
      kafka:
        image: apache/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: rdkafka, redis, mbstring, pdo_sqlite

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Preparar ambiente de teste
        run: |
          mkdir -p database
          touch database/database.sqlite
          chmod 755 database/database.sqlite

      - name: Rodar Migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      - name: Rodar Testes Feature
        env:
          KAFKA_BROKERS: 127.0.0.1:9092

          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          CACHE_DRIVER: redis

          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

          ITAU_API_KEY: ""
          ITAU_API_SECRET: ""
          ITAU_API_ENDPOINT: "https://sandbox.devportal.itau.com.br"

          SANTANDER_API_KEY: ""
          SANTANDER_API_SECRET: ""
          SANTANDER_API_ENDPOINT: "https://trust-sandbox.api.santander.com.br"

          BRADESCO_API_KEY: ""
          BRADESCO_API_SECRET: ""
          BRADESCO_API_ENDPOINT: "https://openapisandbox.prebanco.com.br"

          BANCO_DO_BRASIL_API_KEY: ""
          BANCO_DO_BRASIL_API_SECRET: ""
          BANCO_DO_BRASIL_API_ENDPOINT: "https://sandbox.api.bb.com.br"
        run: php artisan test --testsuite=Feature
